version: '3.3'
services:
    jellyfin:
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        ports:
            - '8096:8096'
            - '8920:8920'
            - '7359:7359/udp'
            - '1900:1900/udp'
        volumes:
            - '$HOME/dockdata/jellyfin:/config'
            - '$HOME/data/tvseries:/data/tvshows'
            - '$HOME/data/movies:/data/movies'
        restart: unless-stopped
        image: 'linuxserver/jellyfin:latest'
    qbittorrent:
        container_name: qbittorrent
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
            - WEBUI_PORT=8090
        ports:
            - '8090:8090'
            - '6881:6881'
            - '6881:6881/udp'
        volumes:
            - '$HOME/dockdata/qbittorrent/appdata/config:/config'
            - '$HOME/dockdata/qbittorrent/downloads:/downloads'
            - '$HOME/data:/data'
        restart: unless-stopped
        image: 'linuxserver/qbittorrent:latest'
    prowlarr:
        container_name: prowlarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/London
        ports:
            - '9696:9696'
        volumes:
            - '$HOME/dockdata/prowlarr:/config'
        restart: unless-stopped
        image: 'linuxserver/prowlarr:develop'
    sonarr:
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        ports:
            - '8989:8989'
        volumes:
            - '$HOME/dockdata/sonarr:/config'
            - '$HOME/data:/data'
            - '$HOME/dockdata/qbittorent/downloads:/downloads'
        restart: unless-stopped
        image: 'linuxserver/sonarr:latest'
    radarr:
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        ports:
            - '7878:7878'
        volumes:
            - '$HOME/dockdata/radarr/data:/config'
            - '$HOME/data:/data'
            - '$HOME/dockdata/qbittorent/downloads:/downloads'
        restart: unless-stopped
        image: 'linuxserver/radarr:latest'